name: lbd
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python>=3.13
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.4
  - numpy
  - pyyaml
  - tqdm
  - pydantic>=2.0
  - pip:
      - wandb
