name: lbd_datagen
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - numpy
  - h5py
  - pyyaml
  - tqdm
  - pydantic>=2.0
  - conda-forge::distgen
  - conda-forge::openpmd-beamphysics
  - conda-forge::bmad
